### ISSUE TITLE
Home Component

### ISSUE THREAD

**Issue by joeypetrone** [joeypetrone/pin-finder#10]
## User Stories

- [x]  As a user, I should see a home page that displays all my properties
- [x] As a user, I should see a button to add new property
- [x]  As a user, I should see a card for each property

## AC
WHEN the page loads
THEN all the properties are displayed
AND a navbar is displayed at the top of the page
AND there is a button that will take me to the new property page
AND there will be a card for each property 

#### Setup
- [x] create a component folder called `Home` -> src/components/pages/Home 
- [x] create a JS file called `Home.js` -> src/components/pages/Home/Home.js
- [x] create a Sass file `Home.scss` -> src/components/pages/Home/Home.scss

#### Sass File
- [x] In Home.scss, set `.Home` to `display: block;`

#### JS File
- [x] Import `React` from `react` at top of page
- [x] Import `{ Link }` from `react-router-dom` for `Add Property` link button
- [x] Import `PropertyCard` from `../../shared/PropertyCard/PropertyCard` #27 
- [x] Import `authData` from `../../../helpers/data/authData` #16 
- [x] import `propertyData` from `../../../helpers/data/propertyData` #4 
- [x] Import `Home` Sass file at top of page
- [x] Create a class called `Home` that extends `React.Component`
- [x] In `state` add `properties: []`, an empty array to add properties to by uid
- [x] Create a function called `getProperties`, that calls `propertyData.getPropertiesByUid().then().catch()` and passes a const variable `uid` that is initailized by `authData.getUid()`
- [x] In the `then((properties))` of the promise, set `state` to `{ properties }`, also handle the `.catch` error
- [x] Create a function called `removeProperty` that has `propertyId` for the parameter  
- [x] In `removeProperty` call the promise `propetyData.deleteProperty()` and pass the `propertyId` 
- [x] In the `.then()` call `this.getProperties` and the `.catch` should handle the error
- [x] Call a `componentDidMount()` and inside call `this.getProperties()`
- [x] In the `render()`, create a `const` variable called `{ properties }` and initialize to `this.state`
- [x] Create a `const` function called `buildPropertyCards`, that maps over the properties array and returns a `<PropertyCard>` JSX
- [x] In the `<PropertyCard>` JSX, props for `key`, `property`, and `removeProperty` function should be set 
- [x] Under the `return ()`, create a `div` with a className of `Home` and an `h1` with `My Properties`, also call `{buildPropertyCards}`
- [x] There should also be a button called `Add Property` above the property cards 
- [x] Export `Home` at bottom of page 
- [x] Refer to `Routing` #15 for location of `Home` Component in the `App` Component
