### ISSUE TITLE
SingleProperty Component

### ISSUE THREAD

**Issue by joeypetrone** [joeypetrone/pin-finder#12]
## User Stories

- [x]  As a user, I should see a map centered on the selected property
- [x] As a user, I should see a button to add pin
- [x]  As a user, I should see a list of all pins below the map

## AC
WHEN the page loads
THEN a map is displayed centered on the selected property 
AND a navbar is displayed at the top of the page
AND there is a a button to add pin that takes you to the new pin page
AND there is a list of all pins for this property underneath the map 

#### Setup
- [x] create a component folder called `SingleProperty` -> src/components/page/SingleProperty 
- [x] create a JS file called `SingleProperty.js` -> src/components/page/SingleProperty/SingleProperty.js
- [x] create a Sass file `SingleProperty.scss` -> src/components/page/SingleProperty/SingleProperty.scss

#### Sass File
- [x] In SingleProperty.scss, set `.SingleProperty` to `display: block;`

#### JS File
- [x] Import `react` at top of page
- [x] Import `{ Link }` from `react-router-dom`
- [x] Import `propertyData` from `../../../helpers/data/propertyData`
- [x] Import `SingleProperty` Sass file
- [x] Create a class called `SingleProperty` that extends `React.Component`
- [x] There should be a `state` that has an empty `property: {}` object
- [x] Use `componentDidMount()` to `setState` of `property` using the promise `propertyData.getSingleProperty()`
- [x] Pass `propertyId` into `.getSingleProperty()`, this can be found at `this.props.match.params`
- [x] Add a function for deleting the property called `removeSingleProperty`, this will be a click event that calls `propertyData.deleteProperty()` and `propertyId` should be passed
- [x] `removeSingleProperty` should `.then()` a route back to the home page `this.props.history.push('/home')`
- [x] Under the `render()`, set variables for `property`, `propertyId`, `editPropertyLink`, and `addPinLink`
- [x] In the `return ()`, add a `div` with `className="SingleProperty"` and any styling necessary
- [x] There should be an `<h3>` with the property name, and `<h4>` with property address
- [x] There should be a button called `Add Pin` that links to the NewPin Component #17 
- [x] There should be a button called `Edit` that links to the EditProperty Component #18 
- [x] There should be a button called `Delete` that calls `removeSingleProperty` when clicked
- [x] There should map component implemented, see the MyMap Component #20 
- [x] All additional information about the property should be nicely displayed above or below the map component
- [x] Below the map component, there should be a list of all the pins associated with this property, see the Pins Component #11 
- [x] Export `SingleProperty` at bottom of page 
- [x] See the Routing ticket for information on the path #15
