### ISSUE TITLE
Routing / App Component

### ISSUE THREAD

**Issue by joeypetrone** [joeypetrone/pin-finder#15]
## DEV NOTES
**Routes** (To be placed in this order in the `<Switch>`)

- [x] Private Route:  path `/home` component `Home` #10 
- [x] Private Route:  path `/property/edit/:propertyId` component `EditProperty` #18 
- [x] Private Route:  path `/pin/edit/:pinId` component `EditPin` #19 
- [x] Private Route:  path `/property/new` component `NewProperty` #14 
- [x] Private Route:  path `/pin/new/:propertyId` component `NewPin` #17 
- [x] Private Route:  path `/property/:propertyId` component `SingleProperty` #12 
- [x] Private Route:  path `/pin/:pinId` component `SinglePin` #13 
- [x] Public Route:  path `/auth` component `Auth` #9 

#### Setup
- [x] Create a folder called App:  `/src/App/`
- [x] Create a file called App.js:  `/src/App/App.js`
- [x] Create a file called App.scss:  `/src/App/App.scss`

#### Sass File
- [x] In App.scss, set `.App` to `display: block;`

#### JS File
- [x] Import `React` from `react` at top of page
- [x] Import `firebase` from `firebase/app` 
- [x] Import `firebase/auth` 
- [x] Import `BrowserRouter, Route, Redirect, Switch` from `react-router-dom` 
- [x] Import `App` Sass file 
- [x] Import `MyNavbar` from `../components/shared/MyNavbar/MyNavbar` #8 
- [x] Import `Auth` from `../components/pages/Auth/Auth` #9 
- [x] Import `Home` from `../components/pages/Home/Home` #10 
- [x] Import `EditProperty` from `../components/pages/EditProperty/EditProperty` #18 
- [x] Import `EditPin` from `../components/pages/EditPin/EditPin` #19 
- [x] Import `NewProperty` from `../components/pages/NewProperty/NewProperty` #14 
- [x] Import `NewPin` from `../components/pages/NewPin/NewPin` #17 
- [x] Import `SingleProperty` from `../components/pages/SingleProperty/SingleProperty` #12 
- [x] Import `SinglePin` from `../components/pages/SinglePin/SinglePin` #13 
- [x] Import `fbConnection` from `../helpers/data/connection` #26 
- [x] Call `fbConnection()`
- [x] Add `PublicRoute` function: 
```javascript
const PublicRoute = ({ component: Component, authed, ...rest }) => {
  const routeChecker = (props) => (authed === false
    ? (<Component {...props} />)
    : (<Redirect to={{ pathname: '/home', state: { from: props.location } }} />));
  return <Route {...rest} render={(props) => routeChecker(props)} />;
};
```
- [x] Add `PrivateRoute` function: 
```javascript
const PrivateRoute = ({ component: Component, authed, ...rest }) => {
  const routeChecker = (props) => (authed === true
    ? (<Component {...props} />)
    : (<Redirect to={{ pathname: '/auth', state: { from: props.location } }} />));
  return <Route {...rest} render={(props) => routeChecker(props)} />;
};
```
- [x] Create a class called `App` that extends `React.Component`
- [x] Set `state` to `authed: false`
- [x] Call `componentDidMount()` and check if user is logged in using `this.removeListener` and `firebase.auth().onAuthStateChanged(user)`
- [x] If user is logged in `setState` to `authed: true` and if no user is logged in `setState` to `authed: false`
- [x] Call `componentWillMount()` to call `this.removeListener()`
- [x] In `render()` initialize `const { authed }` to `this.state`
- [x] In `return`, add `<div className="App">` , `<BrowserRouter>`,`<React.Fragment>`, `<MyNavbar authed={authed}  />` #8 
- [x] Add a container div and any styling divs necessary and then a `<Switch>` 
- [x] Inside the Switch add all the `<PrivateRoute>` and `<PublicRoute>` paths as well as a `<Redirect from="*" to="home" />`
- [x] Export `App` at bottom of page
